// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
export declare function normalizeActor(actor?: string): string;
export declare function setCurrentActor(actor?: string): string;
export declare function getCurrentActor(): string;
