package main

import (
	"fmt"
	"go/ast"
	"go/token"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

const (
	helperDir = envoyDir + "/internal/broker/helper"
	cliDir    = envoyDir + "/cmd/agent-secrets"
)

func frontMatter(title, description, from string) string {
	return fmt.Sprintf("---\ntitle: %s\ndescription: %s\n---\n\n<!-- Generated by packages/envoy/cmd/broker-refgen from %s. Edit that source, not this page. -->\n\n",
		strconv.Quote(title), strconv.Quote(description), from)
}

// api is the broker's HTTP package, read once for the two pages that document it: its functions,
// its routes, the credential each route's adapter needs, and what each route can answer.
type api struct {
	g        *graph
	routes   []route
	classes  []authClass
	outcomes [][]outcome // outcomes[i] is everything routes[i]'s handler can answer
}

func readAPI(root string) (*api, error) {
	g, err := newGraph(root)
	if err != nil {
		return nil, err
	}
	routes, err := readRoutes(g.src, g.funcs)
	if err != nil {
		return nil, err
	}
	classes, err := g.readAuthClasses(routes)
	if err != nil {
		return nil, err
	}
	outcomes := make([][]outcome, len(routes))
	for i, r := range routes {
		if outcomes[i], err = g.handlerOutcomes(r); err != nil {
			return nil, err
		}
	}
	return &api{g: g, routes: routes, classes: classes, outcomes: outcomes}, nil
}

// apiPage is the HTTP API reference: the credentials routes take, then every route with its
// request body, response body and refusals.
func apiPage(a *api) (string, error) {
	g, routes, classes := a.g, a.routes, a.classes
	labels := map[string]string{}
	for _, c := range classes {
		labels[c.Wrapper] = c.Label
	}
	var b strings.Builder
	b.WriteString(frontMatter("HTTP API", "Every route the secrets broker serves, the credential each needs, and what each answers.", apiDir))
	b.WriteString("The broker answers JSON. A refusal is `{\"code\": \"…\", \"error\": \"…\"}` with the HTTP status below; the [error reference](/legion/broker/reference/errors/) lists every code.\n\n")

	b.WriteString("## Authentication\n\nEach route takes one kind of credential, or none. These are the refusals the broker answers for the credential itself, before the route runs.\n\n")
	b.WriteString("| Credential | Description | Refusals |\n| --- | --- | --- |\n")
	for _, c := range classes {
		var refused []string
		for _, o := range refusals(c.Refusals) {
			refused = append(refused, fmt.Sprintf("%d `%s`", o.Status, o.Code))
		}
		if len(refused) == 0 {
			refused = []string{"none"}
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", c.Label, cell(lead(c.Wrapper, c.Doc)), strings.Join(refused, "<br>"))
	}

	b.WriteString("\n## Routes\n\n| Method | Path | Credential | What it does |\n| --- | --- | --- | --- |\n")
	for _, r := range routes {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n", r.Method, r.Pattern, labels[r.Wrapper], cell(r.Summary))
	}

	for i, r := range routes {
		outs := a.outcomes[i]
		fmt.Fprintf(&b, "\n### %s %s\n\n%s\n\n", r.Method, r.Pattern, cell(r.Summary))
		fmt.Fprintf(&b, "- Credential: %s\n", labels[r.Wrapper])
		if params := pathParams.FindAllStringSubmatch(r.Pattern, -1); len(params) > 0 {
			var names []string
			for _, p := range params {
				names = append(names, "`"+p[1]+"`")
			}
			fmt.Fprintf(&b, "- Path parameters: %s\n", strings.Join(names, ", "))
		}
		var queries, bodies, successes, answers []string
		for _, o := range outs {
			switch {
			case o.Query != "":
				queries = union(queries, []string{"`" + o.Query + "`"})
			case o.BodyType != "":
				bodies = union(bodies, []string{o.BodyType})
			case o.Code == "" && o.Status != 0:
				successes = union(successes, []string{fmt.Sprintf("`%d`", o.Status)})
				if o.RespType != "" {
					answers = union(answers, []string{o.RespType})
				}
			}
		}
		if len(queries) > 0 {
			fmt.Fprintf(&b, "- Query parameters: %s\n", strings.Join(queries, ", "))
		}
		if len(successes) > 0 {
			if len(answers) == 0 {
				fmt.Fprintf(&b, "- Success: %s, with no body\n", strings.Join(successes, ", "))
			} else {
				fmt.Fprintf(&b, "- Success: %s\n", strings.Join(successes, ", "))
			}
		}
		fmt.Fprintf(&b, "- Source: `%s`\n", g.src.at(g.funcs[r.Handler]))
		for _, typeName := range bodies {
			ref, err := g.localStruct(typeName)
			if err != nil {
				return "", err
			}
			b.WriteString("\nRequest body (JSON):\n\n")
			if err := g.writeFields(&b, ref, ""); err != nil {
				return "", err
			}
		}
		switch len(answers) {
		case 0:
		case 1:
			ref, err := g.localStruct(answers[0])
			if err != nil {
				return "", err
			}
			b.WriteString("\nResponse body (JSON):\n\n")
			if err := g.writeFields(&b, ref, ""); err != nil {
				return "", err
			}
		default:
			b.WriteString("\nResponse body (JSON), one of:\n")
			for _, typeName := range answers {
				ref, err := g.localStruct(typeName)
				if err != nil {
					return "", err
				}
				doc := prose(ref.spec.Doc)
				if doc == "" {
					if gd := genDeclOf(g.src, ref.spec); gd != nil {
						doc = prose(gd.Doc)
					}
				}
				if doc == "" {
					return "", fmt.Errorf("%s: %s is one of several answers of %s %s, so it needs a doc comment saying when", g.src.at(ref.spec), typeName, r.Method, r.Pattern)
				}
				fmt.Fprintf(&b, "\n%s:\n\n", strings.TrimSuffix(lead(typeName, doc), "."))
				if err := g.writeFields(&b, ref, ""); err != nil {
					return "", err
				}
			}
		}
		if refused := refusals(outs); len(refused) > 0 {
			b.WriteString("\nRefusals:\n\n| Status | Code | Message |\n| --- | --- | --- |\n")
			for _, o := range refused {
				fmt.Fprintf(&b, "| %d | `%s` | %s |\n", o.Status, o.Code, messages(o.Messages))
			}
		}
	}
	return b.String(), nil
}

// localStruct is the struct type the API package declares as name.
func (g *graph) localStruct(name string) (structRef, error) {
	ref, ok, err := g.structOf(g.src, nil, ast.NewIdent(name))
	if err != nil {
		return structRef{}, err
	}
	if !ok {
		return structRef{}, fmt.Errorf("%s declares no struct type %s", apiDir, name)
	}
	return ref, nil
}

// genDeclOf is the declaration holding spec, whose doc comment a lone type spec's is.
func genDeclOf(src *source, spec *ast.TypeSpec) *ast.GenDecl {
	for _, f := range src.files {
		for _, d := range f.Decls {
			if gd, ok := d.(*ast.GenDecl); ok {
				for _, s := range gd.Specs {
					if s == spec {
						return gd
					}
				}
			}
		}
	}
	return nil
}

var pathParams = regexp.MustCompile(`\{([a-z_]+)\}`)

// configPage is the configuration reference.
func configPage(root string) (string, error) {
	vars, err := readConfig(root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(frontMatter("Configuration", "Every environment variable the secrets broker reads, with its default and accepted values.", configDir+" and "+brokerMain))
	b.WriteString("The broker reads its configuration from the environment and refuses to start, naming the variable, when one is missing, malformed or out of range.\n\n")
	b.WriteString("## Variables the broker reads\n\n| Variable | Default | Accepted values | What it sets |\n| --- | --- | --- | --- |\n")
	// Variables one comment documents together (a value and its _FILE, a URL and the password it
	// names) share a row.
	type row struct {
		names              []string
		def, accepted, doc string
	}
	var rows []*row
	byDoc := map[string]*row{}
	for _, v := range vars {
		if v.Removed {
			continue
		}
		r, ok := byDoc[v.Group]
		if !ok {
			r = &row{doc: v.Doc}
			for name := range strings.SplitSeq(v.Group, ", ") {
				r.names = append(r.names, "`"+name+"`")
			}
			byDoc[v.Group] = r
			rows = append(rows, r)
		}
		if v.Default != "" {
			r.def = "`" + v.Default + "`"
		}
		if v.Accepted != "" {
			r.accepted = v.Accepted
		}
	}
	for _, r := range rows {
		def, accepted := r.def, r.accepted
		if def == "" {
			def = "—"
		}
		if accepted == "" {
			accepted = "—"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", strings.Join(r.names, "<br>"), def, accepted, cell(capitalize(r.doc)))
	}
	b.WriteString("\n## Variables the broker refuses\n\nThe broker no longer reads these, and refuses to start while one is set, so a deployment that still sets one fails loudly instead of running on configuration that means nothing.\n\n| Variable | Why |\n| --- | --- |\n")
	for _, v := range vars {
		if v.Removed {
			fmt.Fprintf(&b, "| `%s` | %s |\n", v.Name, cell(capitalize(v.Doc)))
		}
	}
	return b.String(), nil
}

// errorsPage is every code a caller can meet: the HTTP API's, the host helper's, and the
// agent-secrets CLI's exit codes.
func errorsPage(root string, a *api) (string, error) {
	type entry struct {
		statuses, messages, where []string
	}
	codes := map[string]*entry{}
	add := func(o outcome, where string) {
		e, ok := codes[o.Code]
		if !ok {
			e = &entry{}
			codes[o.Code] = e
		}
		e.statuses = union(e.statuses, []string{strconv.Itoa(o.Status)})
		e.messages = union(e.messages, o.Messages)
		e.where = union(e.where, []string{where})
	}
	for _, c := range a.classes {
		for _, o := range refusals(c.Refusals) {
			add(o, fmt.Sprintf("every `%s` route", c.Wrapper))
		}
	}
	for i, r := range a.routes {
		for _, o := range refusals(a.outcomes[i]) {
			add(o, fmt.Sprintf("`%s %s`", r.Method, r.Pattern))
		}
	}

	var b strings.Builder
	b.WriteString(frontMatter("Error codes", "Every refusal code the secrets broker, its host helper and the agent-secrets CLI answer.", apiDir+", "+helperDir+" and "+cliDir))
	b.WriteString("## Broker HTTP API\n\nThe broker refuses a request with an HTTP status and a JSON body `{\"code\": \"…\", \"error\": \"…\"}`. `agent-secrets` prints a refusal as `<error> (<code>)`. A message shown as an error's own text may arrive wrapped in more detail; " + varies + " marks a message built at run time.\n\n")
	b.WriteString("| Code | Status | Message | Where |\n| --- | --- | --- | --- |\n")
	for _, code := range sortedKeys(codes) {
		e := codes[code]
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", code, strings.Join(e.statuses, ", "), messages(e.messages), strings.Join(e.where, "<br>"))
	}

	helperCodes, err := docConsts(root, helperDir, "Code")
	if err != nil {
		return "", err
	}
	b.WriteString("\n## Host helper\n\n`agent-secrets-helper` answers a request it refuses with one of these codes and an error message; `agent-secrets` prints them as `<code>: <error>`.\n\n| Code | Meaning |\n| --- | --- |\n")
	for _, c := range helperCodes {
		fmt.Fprintf(&b, "| `%s` | %s |\n", c.value, cell(lead(c.name, c.doc)))
	}

	exitCodes, err := docConsts(root, cliDir, "exit")
	if err != nil {
		return "", err
	}
	b.WriteString("\n## agent-secrets exit codes\n\n`agent-secrets` exits 0 when it is done and 1 when it failed; these are the other codes it exits with.\n\n| Exit code | Meaning |\n| --- | --- |\n")
	for _, c := range exitCodes {
		fmt.Fprintf(&b, "| %s | %s |\n", c.value, cell(capitalize(c.doc)))
	}
	return b.String(), nil
}

type docConst struct{ name, value, doc string }

// docConsts reads every package-level constant in dir whose name starts with prefix, with its
// doc or line comment, refusing one that has neither.
func docConsts(root, dir, prefix string) ([]docConst, error) {
	src, err := parseDir(root, dir)
	if err != nil {
		return nil, err
	}
	var out []docConst
	for _, f := range src.files {
		for _, d := range f.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs := spec.(*ast.ValueSpec)
				for i, n := range vs.Names {
					if !strings.HasPrefix(n.Name, prefix) || i >= len(vs.Values) {
						continue
					}
					value, ok := strLit(vs.Values[i])
					if !ok {
						lit, isLit := vs.Values[i].(*ast.BasicLit)
						if !isLit {
							return nil, fmt.Errorf("%s: %s is not a literal", src.at(vs), n.Name)
						}
						value = lit.Value
					}
					doc := prose(vs.Doc)
					if doc == "" {
						doc = prose(vs.Comment)
					}
					if doc == "" {
						return nil, fmt.Errorf("%s: %s has no comment saying what it means", src.at(vs), n.Name)
					}
					out = append(out, docConst{name: n.Name, value: value, doc: doc})
				}
			}
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].value < out[j].value })
	return out, nil
}

// cell is text for a Markdown table cell: one line, its pipes escaped, and every "<" outside a
// code span escaped so the renderer cannot read it as an HTML tag.
func cell(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	parts := strings.Split(s, "`")
	for i := range parts {
		parts[i] = strings.ReplaceAll(parts[i], "|", `\|`)
		if i%2 == 0 {
			parts[i] = strings.ReplaceAll(parts[i], "<", "&lt;")
		}
	}
	return strings.Join(parts, "`")
}

// cellCode is text for a code span inside a table cell.
func cellCode(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

func messages(ms []string) string {
	out := make([]string, len(ms))
	for i, m := range ms {
		out[i] = cell(m)
	}
	return strings.Join(out, "<br>")
}

// lead turns a Go doc comment into a table cell's sentence: it drops the opening "name is " or
// "name " the comment names its subject with, and capitalizes what is left.
func lead(name, doc string) string {
	for _, prefix := range []string{name + " is ", name + " "} {
		if rest, ok := strings.CutPrefix(doc, prefix); ok {
			return capitalize(rest)
		}
	}
	return capitalize(doc)
}

func capitalize(s string) string {
	r, size := utf8.DecodeRuneInString(s)
	if size == 0 {
		return s
	}
	return string(unicode.ToUpper(r)) + s[size:]
}
