-- 0023_issue_seen_dispatch_seq.up.sql — the highest Dispatch event sequence intake has observed
-- for an issue, whether or not the event changed anything admission's own fields track.
--
-- last_dispatch_seq advances only on issue.created, issue.updated and issue.closed, the three
-- event types decodeDispatchFact turns into a DispatchIssue observation. Dispatch's own per-issue
-- last_seq advances on every event the issue owns — comments, asks, messages, claims, artifact
-- reviews — so a waiting root deferred at boot against that wider counter could never catch up
-- against last_dispatch_seq alone were its newest event one of those. seen_dispatch_seq tracks the
-- same counter Dispatch's last_seq does, so admission's hold on a deferred candidate can compare
-- like with like and release once the stream has caught the record up to what the boot read saw,
-- however that catching up happened.
alter table issues add column seen_dispatch_seq bigint not null default 0;
