// Code generated by packages/contracts/scripts/gen-go.ts from
// packages/contracts/schemas/dispatch-question.schema.json. DO NOT EDIT.

package core

type DispatchQuestion struct {
	AskID    string                   `json:"askId,omitempty" yaml:"askId,omitempty"`
	Question string                   `json:"question" yaml:"question"`
	Header   string                   `json:"header,omitempty" yaml:"header,omitempty"`
	Options  []DispatchQuestionOption `json:"options,omitempty" yaml:"options,omitempty"`
	Multiple *bool                    `json:"multiple,omitempty" yaml:"multiple,omitempty"`
	Custom   *bool                    `json:"custom,omitempty" yaml:"custom,omitempty"`
}

type DispatchQuestionOption struct {
	Label       string `json:"label" yaml:"label"`
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}
