// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
type TelemetryConfig = {
    windowId?: string;
    documentId?: string;
};
export declare function isTelemetryEnabled(): boolean;
export declare function initTelemetry(_config?: TelemetryConfig): void;
export declare function captureEvent(_event: string, _properties?: Record<string, unknown>): void;
export {};
