// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Text range utilities for ProseMirror documents.
 *
 * Builds a deterministic text index that mirrors `doc.textBetween` so
 * quotes can be resolved to exact document positions without drift.
 */
import type { Node as ProseMirrorNode } from '@milkdown/kit/prose/model';
export interface TextRange {
    from: number;
    to: number;
}
export type TextIndex = {
    text: string;
    positions: Array<number | null>;
};
export declare const DEFAULT_BLOCK_SEPARATOR = "\n";
export declare const DEFAULT_LEAF_TEXT = "\n";
export declare function getTextForRange(doc: ProseMirrorNode, range: TextRange, blockSeparator?: string, leafText?: string): string;
export declare function buildTextIndex(doc: ProseMirrorNode, range?: TextRange, blockSeparator?: string, leafText?: string): TextIndex | null;
export declare function resolveQuoteRange(doc: ProseMirrorNode, quote: string, scope?: TextRange | null, blockSeparator?: string, leafText?: string): TextRange | null;
export declare function resolvePatternRange(doc: ProseMirrorNode, pattern: string, scope?: TextRange | null, blockSeparator?: string, leafText?: string): TextRange | null;
export declare function mapTextOffsetsToRange(index: TextIndex, from: number, to: number): TextRange | null;
