-- 0070_issues_title_lexemes_backfill.up.sql
-- Fills issues.title_lexemes (0069) on every issue stored before it, with the expression the issues
-- trigger writes for every row after it. Setting only that column does not fire the trigger, which
-- reads an update of the key or the title, so search keeps the vector it has.
--
-- An UPDATE takes ROW EXCLUSIVE on issues, which blocks no read, and a row lock on every issue until
-- this transaction commits, so a write that locks an issue's row meanwhile (every event an issue owns
-- takes that lock) waits for it. It changes no key column, so a row that references an issue is
-- written without waiting. Its own migration, so the ACCESS EXCLUSIVE lock 0069 takes is not held
-- while it runs: on 2,905 issues holding production's titles it took 0.58 s at load 85, 0069 3 ms.
update issues set title_lexemes = tsvector_to_array(search_vector('', search_text(title)));
