config:
  envoy:registry: ghcr.io/sjawhar/legion
  envoy:imageTag: 94fdf0276743ea20a021873f81b8fddf27169311
  envoy:natsImage: "nats:2.11-alpine"
  envoy:machines:
    - name: sami-agents-mx
      machineId: sami-agents-mx
      nats:
        serverName: sami-agents-mx
      listener:
        tsnet:
          hostname: envoy-listener-sami-agents-mx
          stateDir: /var/lib/envoy-tsnet/listener-sami-agents-mx
        webhooks:
          github: true
          slack: true
    - name: sami
      sshHost: "ssh://sami@sami"
      machineId: sami
      nats:
        serverName: sami
      listener: {}
    - name: sami-claude
      sshHost: "ssh://claude@sami-claude"
      machineId: sami-claude
      nats:
        serverName: sami-claude
      listener: {}
    - name: ghost-wispr
      sshHost: "ssh://ghost-wispr@ghost-wispr"
      machineId: ghost-wispr
      listener:
        webhooks:
          ghostwispr: true
  envoy:githubWebhookSecret:
    secure: v1:DHpfNE2vubEaxKtd:sDJqUeZA3l2UW4w4NGRLEHKUvLraLygVoWB9MaqagpRBL8lAN5U1tjmZSBNj1COepP3AKYV+OwY=
  envoy:slackSigningSecret:
    secure: v1:jgP6XET6JwLTT8bn:ketvBJemrITJfFxEd42KajyVg9xXGwSUcdBnxM8VluQs+BleTU2Hss0BzjyKuG1R
  envoy:ghcrToken:
    secure: v1:Jx0lqnviYu9cA7rr:3GdTR57rbuNwSFwMJ0MikYKVFXPhoL5gc59iGWy2T0d9iLPCQhixLiW+/vQrHrw9buYpV4rRWko=
encryptionsalt: v1:H2lyi7rkmK8=:v1:Zia1Tn6jUgV/DGFh:NZBFxTMbVeWRm/di9FWg0OUVX3cXNA==
