config:
  envoy:registry: ghcr.io/sjawhar/legion
  envoy:imageTag: 9b3224965ee7
  envoy:natsImage: "nats:2.11-alpine"
  envoy:machines:
    - name: sami-agents-mx
      machineId: sami-agents-mx
      tailscaleIp: "100.117.175.119"
      nats:
        serverName: sami-agents-mx
      listener:
        registryDir: /home/ubuntu/.local/state/opencode/registry
      receivers:
        github: true
        slack: true
    - name: sami
      sshHost: "ssh://sami@sami"
      machineId: sami
      tailscaleIp: "100.100.92.97"
      nats:
        serverName: sami
      listener:
        registryDir: /home/sami/.local/state/opencode/registry
    - name: sami-claude
      sshHost: "ssh://claude@sami-claude"
      machineId: sami-claude
      tailscaleIp: "100.85.18.68"
      nats:
        serverName: sami-claude
      listener:
        registryDir: /home/claude/.local/state/opencode/registry
    - name: ghost-wispr
      sshHost: "ssh://ghost-wispr@ghost-wispr"
      machineId: ghost-wispr
      tailscaleIp: "100.103.243.89"
      listener:
        registryDir: /home/ghost-wispr/.local/state/opencode/registry
      receivers:
        ghostwispr: true
  envoy:githubWebhookSecret:
    secure: v1:ou5S7z5dQpftDzAT:rKMa1g6CsSv/1iGl+vP92mZKUPBPaE5sis0LqHwG4akHkqAW0wNd8C3Lg9ilfHV4lQYYloI1cGM=
  envoy:slackSigningSecret:
    secure: v1:hNaZMeJ90PxT0yhp:5B9aQdgyj2OgnGVW8hhtS5Zvkvhyg5svIjzXeiDtXpjtSFm/cIaV30JX0KnU3e31ew==
  envoy:ghcrToken:
    secure: v1:D4KYv31vCGwPTeKR:ZbyxyiCIs3gJ0A2IUMsG1FIEJ+JlRTkca0P8i6Zvd0bZ8td1M9iUtHGmB5qgBidZKmVHvFx8t/Y=
encryptionsalt: v1:R5vvgmHVgJw=:v1:T7WdS5AO9zYdN0xD:83mEIYvoAB6yLBeqMlWe44tRSwIeIA==
