// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Agent Cursor Plugin for Milkdown
 *
 * Shows a visible cursor and selection for the AI agent that the user can see.
 * The agent cursor is distinct from the user's cursor (different color/style).
 *
 * DESIGN:
 * - Agent cursor is shown as a vertical bar (like a text cursor) in blue
 * - Agent selection is shown as a highlighted range in light blue
 * - Cursor movement is animated so the user can follow along
 * - Agent cursor/selection is separate from user's cursor/selection
 */
import type { EditorView } from '@milkdown/kit/prose/view';
import { type AgentFamily } from '../../ui/agent-identity-icon';
export interface ThinkingChainEntry {
    type: 'thinking' | 'tool_call' | 'tool_result' | 'text' | 'error';
    content?: string;
    toolName?: string;
    timestamp: number;
}
export interface AgentCursorState {
    cursorPos: number | null;
    selectionFrom: number | null;
    selectionTo: number | null;
    isAnimating: boolean;
    agentLabel: string | null;
    agentKind: AgentFamily | null;
    lastUpdated: number | null;
    thinkingChain: ThinkingChainEntry[];
    isThinking: boolean;
    currentAction: string | null;
}
export declare const agentCursorCtx: import("@milkdown/kit/utils").$Ctx<AgentCursorState, "agentCursor">;
/**
 * Agent cursor plugin
 */
export declare const agentCursorPlugin: import("@milkdown/kit/utils").$Prose;
export declare function setAgentCursor(view: EditorView, pos: number, actor?: string): void;
/**
 * Set the agent selection range
 */
export declare function setAgentSelection(view: EditorView, from: number, to: number, actor?: string): void;
/**
 * Clear the agent cursor and selection
 */
export declare function clearAgentCursor(view: EditorView): void;
/**
 * Get current agent cursor state
 */
export declare function getAgentCursorState(view: EditorView): AgentCursorState | null;
/**
 * Show the thinking chain panel
 */
export declare function showThinkingPanel(onCancel?: () => void): void;
/**
 * Hide the thinking chain panel
 */
export declare function hideThinkingPanel(): void;
/**
 * Update the thinking chain display
 */
export declare function updateThinkingChain(entries: ThinkingChainEntry[]): void;
/**
 * Update the current action in the header
 */
export declare function setThinkingAction(action: string | null): void;
export default agentCursorPlugin;
