// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
export declare const authoredTrackerPlugin: import("@milkdown/kit/utils").$Prose;
export default authoredTrackerPlugin;
