// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
import type { DecorationAttrs } from '@milkdown/kit/prose/view';
export declare function installCollabCursorStyles(): void;
export declare function collabCursorBuilder(user: any): HTMLElement;
export declare function collabSelectionBuilder(user: any): DecorationAttrs;
