// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
export type CommentUiMode = 'legacy' | 'v2' | 'auto';
export declare const COMMENT_UI_MODE_QUERY_KEY = "commentUi";
export declare const COMMENT_UI_MODE_STORAGE_KEY = "proofeditor.commentUi";
export declare const COMMENT_UI_MODE_WIDTH_FALLBACK_PX = 900;
export declare function getCommentUiMode(): CommentUiMode;
export declare function shouldUseCommentUiV2(): boolean;
