// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
import { type EditorView } from '@milkdown/kit/prose/view';
export type FindHighlightRange = {
    from: number;
    to: number;
};
export declare function setFindHighlights(view: EditorView, matches: FindHighlightRange[], currentIndex: number): void;
export declare function clearFindHighlights(view: EditorView): void;
export declare const findHighlightsPlugin: import("@milkdown/kit/utils").$Prose;
