// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Heat Map Decorations Plugin for Milkdown
 *
 * Visualizes authorship using a continuous colored bar in the left gutter.
 *
 * PERFORMANCE DESIGN:
 * - Segments are calculated relative to DOCUMENT position (not viewport)
 * - On scroll, we just update a CSS transform (GPU accelerated)
 * - Full recalculation only happens on document changes
 */
export type HeatMapMode = 'hidden' | 'subtle' | 'background' | 'full';
export interface HeatMapState {
    mode: HeatMapMode;
}
export declare const heatmapCtx: import("@milkdown/kit/utils").$Ctx<HeatMapState, "heatmap">;
export declare const heatmapPlugin: import("@milkdown/kit/utils").$Prose;
export default heatmapPlugin;
