// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
import type { EditorView } from '@milkdown/kit/prose/view';
import { type MarkRange } from './marks';
export type CommentPopoverDraftSnapshot = {
    mode: 'composer';
    range: MarkRange;
    by: string;
    text: string;
} | {
    mode: 'thread';
    markId: string;
    by: string;
    text: string;
};
export declare function openCommentComposer(view: EditorView, range: MarkRange, by: string): void;
export declare function captureCommentPopoverDraft(view: EditorView): CommentPopoverDraftSnapshot | null;
export declare function restoreCommentPopoverDraft(view: EditorView, snapshot: CommentPopoverDraftSnapshot): boolean;
export declare const markPopoverPlugin: import("@milkdown/kit/utils").$Prose;
