// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
export type VisualViewportLike = {
    height: number;
    offsetTop: number;
} | null;
export declare function getViewportOffset(layoutHeight: number, vv: VisualViewportLike): number;
export declare function getVisualViewportHeight(layoutHeight: number, vv: VisualViewportLike): number;
