// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
export type LinkTargetLike = {
    getAttribute: (name: string) => string | null;
};
export type LinkClickEventLike = Pick<MouseEvent, 'button' | 'metaKey' | 'ctrlKey' | 'defaultPrevented'>;
export type LinkModifierEventLike = Pick<MouseEvent, 'metaKey' | 'ctrlKey'>;
export type LinkActionCardState = {
    openLabel: string;
    modifierTitle: string;
    armed: boolean;
};
export declare function shouldOpenLinkForEvent(event: LinkClickEventLike, isEditable: boolean): boolean;
export declare function isLinkModifierActive(event: LinkModifierEventLike): boolean;
export declare function getEditModeLinkCardState(isMac: boolean, modifierActive: boolean): LinkActionCardState;
export declare function normalizeAndValidateHref(rawHref: string, baseHref?: string): string | null;
export declare function extractLinkTargetFromEvent(event: Pick<MouseEvent, 'target'>): LinkTargetLike | null;
export declare const markdownLinkClickPlugin: import("@milkdown/kit/utils").$Prose;
export default markdownLinkClickPlugin;
