// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Unified Marks Plugin for ProseMirror/Milkdown
 *
 * Anchors live as inline marks in the document (portable Markdown spans).
 * Metadata (comment text, suggestion content/status) lives in the PROOF block.
 */
import { PluginKey } from '@milkdown/kit/prose/state';
import type { EditorState } from '@milkdown/kit/prose/state';
import type { EditorView } from '@milkdown/kit/prose/view';
import type { Node as ProseMirrorNode } from '@milkdown/kit/prose/model';
import { type Mark, type MarkRange, type SuggestionStatus, type StoredMark, type OrchestratedMarkMeta } from '../../formats/marks.js';
export interface MarksPluginState {
    metadata: Record<string, StoredMark>;
    activeMarkId: string | null;
    composeAnchorRange?: MarkRange | null;
}
export declare const marksPluginKey: PluginKey<MarksPluginState>;
export declare const marksCtx: import("@milkdown/kit/utils").$Ctx<MarksPluginState, "marks">;
export interface ResolvedMark extends Mark {
    resolvedRange: {
        from: number;
        to: number;
    } | null;
    resolvedRanges?: MarkRange[];
}
type MarkAnchorHydrationFailure = {
    docFingerprint: string;
    lastAttemptAt: number;
};
export declare function __getMarkAnchorHydrationFailure(id: string): MarkAnchorHydrationFailure | null;
export declare function __resetMarkAnchorHydrationFailures(): void;
export declare function __getMarkAnchorHydrationFailureCount(): number;
export declare function rangeCrossesTableCellBoundary(doc: ProseMirrorNode, range: MarkRange): boolean;
export declare function debugResolveRangeWithValidation(doc: ProseMirrorNode, quote: string, range?: MarkRange): {
    ok: boolean;
    reason: 'unresolved' | 'range-quote-mismatch-re-resolve-failed' | 'range-quote-mismatch-re-resolve-midword' | 'midword-re-resolve-failed' | 'midword-re-resolve-still-midword' | 'resolved';
    rangeProvided: boolean;
    requestedRange: MarkRange | null;
    resolvedRange: MarkRange | null;
    actualQuote: string;
    expectedNormalized: string;
    actualNormalized: string;
    mismatch: boolean;
    midWord: boolean;
};
export declare function setEventCallback(cb: (event: string, data: Record<string, unknown>) => void): void;
export declare function getMarks(state: EditorState): Mark[];
export declare function getActiveMarkId(state: EditorState): string | null;
export declare function getComposeAnchorRange(state: EditorState): MarkRange | null;
export declare function getMarkMetadata(state: EditorState): Record<string, StoredMark>;
export declare function getMarkMetadataForDisk(state: EditorState): Record<string, StoredMark>;
/** Like getMarkMetadata but includes `quote` for each mark — needed for share sync
 *  so remote clients can recreate ProseMirror anchors using quote-based range resolution. */
export declare function getMarkMetadataWithQuotes(state: EditorState): Record<string, StoredMark>;
export declare function mergePendingServerMarks(localMetadata: Record<string, StoredMark>, serverMarks: Record<string, StoredMark>): Record<string, StoredMark>;
export declare function buildSuggestionMetadata(kind: 'insert' | 'delete' | 'replace', by: string, content: string | null, createdAt?: string, status?: SuggestionStatus, orchestrationMeta?: OrchestratedMarkMeta): StoredMark;
export declare function setMarkMetadata(view: EditorView, metadata: Record<string, StoredMark>): void;
/** Apply marks from a remote client (share sync).
 *  Optionally creates ProseMirror anchors for marks that don't already exist in the document,
 *  using the `quote` field to resolve text ranges. Then merges all metadata. */
export declare function applyRemoteMarks(view: EditorView, metadata: Record<string, StoredMark>, options?: {
    hydrateAnchors?: boolean;
}): void;
export declare function setActiveMark(view: EditorView, markId: string | null): void;
export declare function setComposeAnchorRange(view: EditorView, range: MarkRange | null): void;
export declare function approve(view: EditorView, quote: string, by: string, range?: MarkRange): Mark | null;
export declare function unapprove(view: EditorView, quote: string, by: string): boolean;
export declare function flag(view: EditorView, quote: string, by: string, note?: string, range?: MarkRange): Mark | null;
export declare function unflag(view: EditorView, quote: string, by: string): boolean;
export declare function comment(view: EditorView, quote: string, by: string, text: string, range?: MarkRange, meta?: OrchestratedMarkMeta): Mark;
export declare function reply(view: EditorView, markId: string, by: string, text: string): Mark | null;
export declare function resolve(view: EditorView, markId: string): boolean;
export declare function unresolve(view: EditorView, markId: string): boolean;
export declare function suggestInsert(view: EditorView, quote: string, by: string, content: string, range?: MarkRange, meta?: OrchestratedMarkMeta): Mark | null;
export declare function suggestDelete(view: EditorView, quote: string, by: string, range?: MarkRange, meta?: OrchestratedMarkMeta): Mark | null;
export declare function suggestReplace(view: EditorView, quote: string, by: string, content: string, range?: MarkRange, meta?: OrchestratedMarkMeta, parser?: MarkdownParser): Mark | null;
export declare function debugAnalyzeReplace(view: EditorView, quote: string, content: string, range?: MarkRange, parser?: MarkdownParser): {
    resolution: {
        range: MarkRange | null;
        actualQuote: string;
        rangeProvided: boolean;
    };
    structural: ReturnType<typeof resolveStructuralReplaceRange> | null;
    tableCellBoundaryCrossed: boolean;
};
export declare function modifySuggestionContent(view: EditorView, markId: string, newContent: string): boolean;
export declare function setDefaultMarkdownParser(parser?: MarkdownParser): void;
declare function resolveStructuralReplaceRange(doc: ProseMirrorNode, range: MarkRange, markdown: string, parser?: MarkdownParser): {
    range: MarkRange;
    structural: boolean;
    safe: boolean;
    upgraded: boolean;
    reason?: string;
};
export declare function accept(view: EditorView, markId: string, parser?: MarkdownParser): boolean;
export declare function reject(view: EditorView, markId: string): boolean;
export declare function acceptAll(view: EditorView, parser?: MarkdownParser): number;
export declare function rejectAll(view: EditorView): number;
export declare function deleteMark(view: EditorView, markId: string): boolean;
export declare function addAuthoredMark(view: EditorView, by: string, range: MarkRange, quote?: string): Mark;
export declare function setAuthoredMark(view: EditorView, by: string, range: MarkRange): Mark;
export declare function getAuthorshipStats(view: EditorView): {
    humanPercent: number;
    aiPercent: number;
    humanChars: number;
    aiChars: number;
};
export declare function coalesceMarks(view: EditorView): void;
export declare function updateMarksAfterEdit(_view: EditorView, _editFrom: number, _editTo: number, _newLength: number): void;
export declare function resolveMarks(doc: ProseMirrorNode, marks: Mark[]): ResolvedMark[];
export declare const marksPlugin: import("@milkdown/kit/utils").$Prose;
export declare const marksPlugins: (import("@milkdown/kit/utils").$Prose | import("@milkdown/kit/utils").$Ctx<MarksPluginState, "marks">)[];
export type { Mark, MarkKind, MarkRange, CommentData, InsertData, DeleteData, ReplaceData, StoredMark, } from '../../formats/marks.js';
export { extractMarks, embedMarks, hasMarks, getMarksByKind, getPendingSuggestions, getUnresolvedComments, getAuthoredMarks, getHumanAuthored, getAIAuthored, getActiveMarks, getOrphanedMarks, findMark, isHuman, isAI, getActorName, createAuthored, coalesceAuthoredMarks, calculateAuthorshipStats, resolveQuote, } from '../../formats/marks.js';
