// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
export declare function isMermaidCodeBlockLanguage(language: unknown): boolean;
export declare function validateMermaidSource(source: string): void;
export declare function renderProofMermaidSvg(source: string): string;
export declare const mermaidDiagramsPlugin: import("@milkdown/kit/utils").$Prose;
