// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
type ShareRuntimeCapabilities = {
    canComment: boolean;
    canEdit: boolean;
};
export declare function setShareRuntimeCapabilities(capabilities: Partial<ShareRuntimeCapabilities>): void;
export declare function resetShareRuntimeCapabilities(): void;
export declare function canCommentInRuntime(): boolean;
export declare function canEditInRuntime(): boolean;
export {};
