// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
import type { EditorView } from '@milkdown/kit/prose/view';
export declare const SHARE_CONTENT_FILTER_ALLOW_META = "proof.share.allowContentMutation";
/**
 * When enabled, blocks text-editing transactions while allowing mark changes.
 * This lets web viewers select text and add comments/flags/suggestions
 * without being able to edit the prose content itself.
 *
 * Allowed: AddMarkStep, RemoveMarkStep (comments, flags, etc.)
 * Blocked: ReplaceStep, ReplaceAroundStep (typing, paste, delete)
 */
export declare function enableShareContentFilter(view: EditorView): void;
export declare function disableShareContentFilter(view: EditorView): void;
export declare const shareContentFilterPlugin: import("@milkdown/kit/utils").$Prose;
