// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Suggestions Plugin for Milkdown
 *
 * Converts edits into proofSuggestion marks + PROOF metadata
 * when suggestions mode is enabled.
 */
import { PluginKey, type EditorState, type Transaction } from '@milkdown/kit/prose/state';
export interface SuggestionState {
    enabled: boolean;
}
export declare const suggestionsPluginKey: PluginKey<SuggestionState>;
export declare const suggestionsCtx: import("@milkdown/kit/utils").$Ctx<SuggestionState, "suggestions">;
/**
 * Wrap a transaction to convert edits to suggestions when enabled.
 * This intercepts the transaction and converts direct edits into tracked changes:
 * - Insertions get marked with proofSuggestion kind=insert
 * - Deletions get marked with proofSuggestion kind=delete instead of being removed
 * - Replacements become proofSuggestion kind=replace with content stored in metadata
 */
export declare function wrapTransactionForSuggestions(tr: Transaction, state: EditorState, enabled: boolean): Transaction;
/**
 * Check if suggestions are enabled
 */
export declare function isSuggestionsEnabled(state: EditorState): boolean;
/**
 * Enable suggestions
 */
export declare function enableSuggestions(view: {
    state: EditorState;
    dispatch: (tr: Transaction) => void;
}): void;
/**
 * Disable suggestions
 */
export declare function disableSuggestions(view: {
    state: EditorState;
    dispatch: (tr: Transaction) => void;
}): void;
/**
 * Toggle suggestions
 */
export declare function toggleSuggestions(view: {
    state: EditorState;
    dispatch: (tr: Transaction) => void;
}): boolean;
/**
 * Create the suggestions plugin
 */
export declare const suggestionsPlugin: import("@milkdown/kit/utils").$Prose;
/**
 * Export all for use in editor
 */
export declare const suggestionsPlugins: (import("@milkdown/kit/utils").$Prose | import("@milkdown/kit/utils").$Ctx<SuggestionState, "suggestions">)[];
