// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Table Keyboard Plugin
 *
 * Two-step Backspace behavior for table rows:
 * 1. Empty rows: Backspace deletes the row immediately
 * 2. Cursor at start of first cell: Backspace selects the entire row (native selection)
 * 3. Entire row already selected: Backspace deletes the row
 *
 * Uses TextSelection (native browser highlight) instead of CellSelection
 * so the selection looks like a normal system selection.
 */
import type { EditorView } from '@milkdown/kit/prose/view';
/** Core handler — exported for programmatic testing */
export declare function handleTableBackspace(view: EditorView): boolean;
export declare const tableKeyboardPlugin: import("@milkdown/kit/utils").$Prose;
