// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
import { type Transaction } from '@milkdown/kit/prose/state';
import { type EditorView } from '@milkdown/kit/prose/view';
import type { Node as ProseMirrorNode } from '@milkdown/kit/prose/model';
export declare function shouldRebuildTaskCheckboxDecorations(tr: Transaction, oldDoc: ProseMirrorNode, newDoc: ProseMirrorNode): boolean;
export declare function toggleTaskAtPos(view: EditorView, pos: number): boolean;
export declare function handleTaskCheckboxEvent(view: EditorView, event: Event): boolean;
export declare function handleTaskCheckboxKeydown(view: EditorView, event: KeyboardEvent): boolean;
export declare const taskCheckboxesPlugin: import("@milkdown/kit/utils").$Prose;
