// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Code Block Schema Extension
 *
 * Extends the default code_block schema to allow proof marks on code blocks.
 * Marks are encoded in the fence meta and restored on parse.
 */
export declare const codeBlockAttrExt: import("@milkdown/kit/utils").$NodeAttr;
export declare const codeBlockSchemaExt: import("@milkdown/kit/utils").$NodeSchema<"code_block">;
export declare const codeBlockExtPlugins: (import("@milkdown/kit/utils").$NodeAttr | import("@milkdown/kit/utils").$NodeSchema<"code_block">)[];
