// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Frontmatter Schema
 *
 * Adds YAML frontmatter support so it round-trips without being rewritten
 * as a horizontal rule + paragraphs.
 */
export declare function stripFrontmatterDelimiters(text: string): string;
export declare function wrapFrontmatterValue(value: string): string;
export declare const frontmatterSchema: import("@milkdown/kit/utils").$NodeSchema<"frontmatter">;
