// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Proof Mark Schemas
 *
 * Anchors for suggestions, comments, review marks, and authored marks.
 * Serialized as inline HTML spans with data-proof attributes.
 */
export declare const proofSuggestionAttr: import("@milkdown/kit/utils").$MarkAttr;
export declare const proofSuggestionSchema: import("@milkdown/kit/utils").$MarkSchema<"proofSuggestion">;
export declare const proofCommentAttr: import("@milkdown/kit/utils").$MarkAttr;
export declare const proofCommentSchema: import("@milkdown/kit/utils").$MarkSchema<"proofComment">;
export declare const proofFlaggedAttr: import("@milkdown/kit/utils").$MarkAttr;
export declare const proofFlaggedSchema: import("@milkdown/kit/utils").$MarkSchema<"proofFlagged">;
export declare const proofApprovedAttr: import("@milkdown/kit/utils").$MarkAttr;
export declare const proofApprovedSchema: import("@milkdown/kit/utils").$MarkSchema<"proofApproved">;
export declare const proofAuthoredAttr: import("@milkdown/kit/utils").$MarkAttr;
export declare const proofAuthoredSchema: import("@milkdown/kit/utils").$MarkSchema<"proofAuthored">;
export declare const proofMarkPlugins: (import("@milkdown/kit/utils").$MarkAttr | import("@milkdown/kit/utils").$MarkSchema<"proofSuggestion"> | import("@milkdown/kit/utils").$MarkSchema<"proofComment"> | import("@milkdown/kit/utils").$MarkSchema<"proofFlagged"> | import("@milkdown/kit/utils").$MarkSchema<"proofApproved"> | import("@milkdown/kit/utils").$MarkSchema<"proofAuthored">)[];
