// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Milkdown plugin for remark-proof-marks
 *
 * Uses $remark to properly integrate the remark plugin with Milkdown's
 * parsing pipeline.
 */
/**
 * Milkdown plugin that integrates remarkProofMarks with the parsing pipeline.
 * This ensures the remark plugin runs during both parsing and serialization.
 *
 * Note: $remark expects () => () => transformer signature
 */
export declare const remarkProofMarksPlugin: import("@milkdown/kit/utils").$Remark<"remarkProofMarks", unknown>;
