#!/usr/bin/env bash
# docs/site/generators/broker-cli.sh <content dir>
#
# Writes <content dir>/broker/reference/cli.md: the help agent-secrets and agent-secrets-helper
# print, every form of it, captured from the binaries on PATH (docs/site/scripts/build-binaries.sh
# builds them from this checkout). The forms come from agent-secrets --help itself, and a form
# whose -h does not exit 0 fails the build, so the page cannot leave one out.
set -euo pipefail
# shellcheck source=SCRIPTDIR/lib/fence.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/fence.sh"

content_dir="${1:?usage: broker-cli.sh <content dir>}"
out="$content_dir/broker/reference/cli.md"
mkdir -p "$(dirname "$out")"
trap 'rm -f "$out.tmp"' EXIT

# Help never depends on the caller's environment: keygen's --out default, for one, is
# AGENT_SECRETS_KEY_DIR, so each binary runs with PATH alone.
clean() { env -i PATH="$PATH" "$@" 2>&1; }

# help prints one form's help, refusing a form whose help exits nonzero.
help() {
  local text
  if ! text="$(clean "$@")"; then
    echo "broker-cli.sh: '$*' exited nonzero; every form must answer --help with exit 0" >&2
    printf '%s\n' "$text" >&2
    exit 1
  fi
  printf '%s\n' "$text"
}

# fenced prints text in a code block that no line of the text can close early.
fenced() {
  local ticks
  ticks=$(fence <<<"$1")
  printf '%stext\n%s\n%s\n' "$ticks" "$1" "$ticks"
}

# form_help prints one form's help in a fenced block.
form_help() {
  local text
  text="$(help "$@")"
  fenced "$text"
}

usage="$(help agent-secrets --help)"
{
  cat <<'EOF'
---
title: "agent-secrets CLI"
description: "Every form of agent-secrets and agent-secrets-helper, as the built binaries describe themselves."
---

<!-- Generated by docs/site/generators/broker-cli.sh from the built agent-secrets and agent-secrets-helper help. Edit their help text, not this page. -->

`agent-secrets` is the command an agent session runs to use a secret; `agent-secrets-helper` is
the per-user daemon that signs for a host's agent sessions. This page is their own help.

## agent-secrets

EOF
  fenced "$usage"
  # Each "  agent-secrets <form>" line of the usage names a form: one or two lowercase words
  # (launcher login), or NAME... for the form that runs a command with secrets.
  while IFS= read -r line; do
    if [[ "$line" =~ ^\ \ agent-secrets\ ([a-z][a-z-]*)(\ [a-z][a-z-]*)?(\ |$) ]]; then
      form="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
      printf '\n### agent-secrets %s\n\n' "$form"
      # shellcheck disable=SC2086 # a two-word form is two arguments
      form_help agent-secrets $form --help
    elif [[ "$line" =~ ^\ \ agent-secrets\ NAME ]]; then
      printf '\n### agent-secrets NAME... -- command\n\n'
      form_help agent-secrets NAME --help -- true
    fi
  done <<<"$usage"
  printf '\n## agent-secrets-helper\n\n'
  form_help agent-secrets-helper --help
} >"$out.tmp"
mv "$out.tmp" "$out"
