// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
export declare const AGENT_FACE_VARIANTS: readonly ["blue", "lime", "mint", "orange", "pink", "purple", "red", "yellow"];
export type AgentFamily = (typeof AGENT_FACE_VARIANTS)[number];
export type AgentFaceVariant = AgentFamily;
type AgentIdentityInput = {
    id?: unknown;
    name?: unknown;
    skill?: unknown;
    actor?: unknown;
    avatar?: unknown;
};
type AgentFacePalette = {
    variant: AgentFaceVariant;
    accent: string;
    ring: string;
    shadow: string;
};
type AgentFaceMarkupOptions = {
    family?: AgentFamily;
    input?: AgentIdentityInput;
    size?: number;
    className?: string;
    title?: string;
};
type AgentFaceElementOptions = AgentFaceMarkupOptions & {
    wrapperClassName?: string;
};
export declare function resolveAgentFamily(input: AgentIdentityInput): AgentFamily;
export declare function assignDistinctAgentFamilies(agentIds: Iterable<string>): Map<string, AgentFamily>;
export declare function isAgentIdentity(input: AgentIdentityInput): boolean;
export declare function getAgentFaceVariant(family: AgentFamily): AgentFaceVariant;
export declare function getAgentFacePalette(family: AgentFamily): AgentFacePalette;
export declare function getAgentFaceAssetUrl(family: AgentFamily): string;
export declare function createAgentFaceSvgMarkup(options?: AgentFaceMarkupOptions): string;
export declare function createAgentFaceElement(options?: AgentFaceElementOptions): HTMLSpanElement;
export declare function resetAgentFaceAssignmentsForTests(): void;
export {};
