// Runs every reference generator before the site builds. The contract, which
// src/content/docs/contributing.md states for page authors:
//
//   - A generator is a direct entry of docs/site/generators/ named `<section>-<name>.ts` or
//     `<section>-<name>.sh`, executable, where `<section>` is a directory of src/content/docs/.
//     Subdirectories of generators/ hold shared helpers and are never run.
//   - It runs from the repository root as `<generator> <absolute content dir>` (a `.ts` one through
//     Bun), with the Go binaries scripts/build-binaries.sh builds first on its PATH.
//   - It writes its pages under `<content dir>/<section>/reference/`, which this script empties
//     before any generator runs and which git ignores, so a generated page is never committed.
//   - A generator that exits non-zero, or writes no page, fails the build.
import { spawnSync } from "node:child_process";
import {
  accessSync,
  constants,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative, resolve } from "node:path";

const siteDir = resolve(import.meta.dirname, "..");
const repoRoot = resolve(siteDir, "../..");
const contentDir = join(siteDir, "src/content/docs");
const generatorsDir = join(siteDir, "generators");
const binDir = join(siteDir, ".bin");
const GENERATOR_NAME = /^(?<section>[a-z]+)-(?<name>[a-z0-9][a-z0-9-]*)\.(?<ext>ts|sh)$/;
// Hides the generated directory from its section's autogenerated list (starlight-auto-sidebar);
// astro.config.mjs shows it instead as the section's last group, Reference.
const REFERENCE_META = "hidden: true\n";

interface Generator {
  file: string;
  path: string;
  section: string;
  ext: string;
}

function fail(message: string): never {
  console.error(`docs generate: ${message}`);
  process.exit(1);
}

function isExecutable(path: string): boolean {
  try {
    accessSync(path, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function pagesUnder(dir: string): Set<string> {
  if (!existsSync(dir)) return new Set();
  const entries = readdirSync(dir, { recursive: true, withFileTypes: true });
  return new Set(
    entries
      .filter((entry) => entry.isFile() && /\.mdx?$/.test(entry.name))
      .map((entry) => join(entry.parentPath, entry.name))
  );
}

function findGenerators(): Generator[] {
  const problems: string[] = [];
  const generators: Generator[] = [];
  for (const entry of readdirSync(generatorsDir, { withFileTypes: true })) {
    if (entry.isDirectory()) continue;
    const path = join(generatorsDir, entry.name);
    const match = GENERATOR_NAME.exec(entry.name);
    if (!match?.groups) {
      problems.push(`${entry.name} is not named <section>-<name>.ts or <section>-<name>.sh`);
      continue;
    }
    const { section, ext } = match.groups;
    const sectionDir = join(contentDir, section);
    if (!existsSync(sectionDir) || !statSync(sectionDir).isDirectory()) {
      problems.push(
        `${entry.name} names section "${section}", but ${relative(repoRoot, sectionDir)} is not a directory`
      );
      continue;
    }
    if (!isExecutable(path)) {
      problems.push(`${entry.name} is not executable (chmod +x it)`);
      continue;
    }
    generators.push({ file: entry.name, path, section, ext });
  }
  if (problems.length > 0) {
    fail(`generators/ has ${problems.length} problem(s):\n  ${problems.join("\n  ")}`);
  }
  return generators.sort((a, b) => a.file.localeCompare(b.file));
}

function run(command: string, args: string[], env: NodeJS.ProcessEnv = process.env): number {
  const result = spawnSync(command, args, { cwd: repoRoot, env, stdio: "inherit" });
  if (result.error) fail(`could not run ${command}: ${result.error.message}`);
  return result.status ?? 1;
}

const generators = findGenerators();

for (const entry of readdirSync(contentDir, { withFileTypes: true })) {
  if (entry.isDirectory()) {
    rmSync(join(contentDir, entry.name, "reference"), { recursive: true, force: true });
  }
}
for (const section of new Set(generators.map((generator) => generator.section))) {
  const referenceDir = join(contentDir, section, "reference");
  mkdirSync(referenceDir, { recursive: true });
  writeFileSync(join(referenceDir, "_meta.yml"), REFERENCE_META);
}

if (run(join(siteDir, "scripts/build-binaries.sh"), [binDir]) !== 0) {
  fail("scripts/build-binaries.sh failed");
}

const env = { ...process.env, PATH: `${binDir}:${process.env.PATH ?? ""}` };
for (const generator of generators) {
  const referenceDir = join(contentDir, generator.section, "reference");
  const before = pagesUnder(referenceDir);
  console.log(`docs generate: running generators/${generator.file}`);
  const status =
    generator.ext === "ts"
      ? run(process.execPath, [generator.path, contentDir], env)
      : run(generator.path, [contentDir], env);
  if (status !== 0) fail(`generators/${generator.file} failed (exit ${status})`);
  const written = [...pagesUnder(referenceDir)].filter((page) => !before.has(page));
  if (written.length === 0) {
    fail(
      `generators/${generator.file} exited 0 but wrote no page under ${relative(repoRoot, referenceDir)}/`
    );
  }
  for (const page of written) console.log(`  wrote ${relative(siteDir, page)}`);
}
console.log(`docs generate: ${generators.length} generator(s) ran`);
