/**
 * Rebuilds `upstream/`, the declarations for the upstream editor modules this package imports.
 *
 * proof-sdk ships TypeScript sources and no declarations, and those sources do not type-check
 * (see AGENTS.md § The upstream boundary), so no consumer's tsc program may open them. `tsc
 * --emitDeclarationOnly --noCheck` reads them anyway — it infers and writes the declarations
 * without reporting the tree's own errors — and what it writes is the real shape of every value
 * and type crossing the boundary.
 *
 *   bun scripts/upstream-declarations.ts          # rewrite upstream/
 *   bun scripts/upstream-declarations.ts --check  # exit 1 when upstream/ is not what the pin emits
 *
 * `tests/upstream-declarations.test.ts` runs `--check`, so a moved pin that changes the surface
 * fails until `upstream/` is rebuilt.
 */
import { mkdirSync, readdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative, resolve, sep } from "node:path";
import type TypeScript from "typescript";

const require = createRequire(import.meta.url);
const ts: typeof TypeScript = require("typescript");

const packageRoot = resolve(import.meta.dir, "..");
const outDir = join(packageRoot, "upstream");
const upstreamSrc = join(
  realpathSync(join(packageRoot, "node_modules", "proof-sdk-upstream")),
  "src"
);

const BANNER = [
  "// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.",
  "// Do not edit; run `bun run upstream-declarations` after moving the pin.",
  "",
].join("\n");

/** The upstream modules this package imports, i.e. the surface the declarations must cover. */
function entryModules(): string[] {
  const specifier = /["']proof-sdk-upstream\/src\/([^"']+)["']/g;
  const found = new Set<string>();
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(path);
      } else if (/\.(ts|tsx|js)$/.test(entry.name)) {
        for (const [, module] of readFileSync(path, "utf8").matchAll(specifier)) {
          found.add(join(upstreamSrc, `${module.replace(/\.js$/, "")}.ts`));
        }
      }
    }
  };
  walk(join(packageRoot, "src"));
  if (found.size === 0) throw new Error("no proof-sdk-upstream imports found under src/");
  return [...found].sort();
}

const options: TypeScript.CompilerOptions = {
  target: ts.ScriptTarget.ES2022,
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  lib: ["lib.es2022.d.ts", "lib.dom.d.ts", "lib.dom.iterable.d.ts"],
  strict: true,
  skipLibCheck: true,
  declaration: true,
  emitDeclarationOnly: true,
  noCheck: true,
  rootDir: upstreamSrc,
  outDir,
};

/**
 * Declarations for the whole closure, not just the entry modules: tsc emits only for the files
 * it was handed as roots when the rest resolve out of node_modules, so the first program is read
 * for its file list and the second one emits from it.
 */
function emit(): Map<string, string> {
  const roots = entryModules();
  const closure = ts
    .createProgram(roots, { ...options, noEmit: true })
    .getSourceFiles()
    .filter((file) => !file.isDeclarationFile && file.fileName.startsWith(`${upstreamSrc}${sep}`))
    .map((file) => file.fileName)
    .sort();

  const written = new Map<string, string>();
  const host = ts.createCompilerHost(options);
  const capture: TypeScript.WriteFileCallback = (fileName, text) => {
    written.set(relative(outDir, fileName).split(sep).join("/"), BANNER + text);
  };
  const result = ts.createProgram(closure, options, host).emit(undefined, capture);
  const errors = result.diagnostics.filter((d) => d.category === ts.DiagnosticCategory.Error);
  if (errors.length > 0) throw new Error(ts.formatDiagnostics(errors, host));
  return written;
}

function committed(): Map<string, string> {
  const files = new Map<string, string>();
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else files.set(relative(outDir, path).split(sep).join("/"), readFileSync(path, "utf8"));
    }
  };
  try {
    walk(outDir);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  return files;
}

const emitted = emit();

if (process.argv.includes("--check")) {
  const onDisk = committed();
  const differences: string[] = [];
  for (const [name, text] of emitted) {
    if (!onDisk.has(name)) differences.push(`missing: upstream/${name}`);
    else if (onDisk.get(name) !== text) differences.push(`stale: upstream/${name}`);
  }
  for (const name of onDisk.keys()) {
    if (!emitted.has(name)) differences.push(`orphan: upstream/${name}`);
  }
  if (differences.length > 0) {
    console.error(
      `upstream/ does not match the pinned sources:\n  ${differences.join("\n  ")}\n` +
        "Run `bun run upstream-declarations` in packages/proof-editor."
    );
    process.exit(1);
  }
  console.log(`upstream/ matches the pin (${emitted.size} declarations).`);
} else {
  rmSync(outDir, { recursive: true, force: true });
  for (const [name, text] of emitted) {
    const path = join(outDir, name);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
  }
  console.log(`wrote ${emitted.size} declarations to upstream/`);
}
