// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * Unified Marks System
 *
 * Everything is a mark - approvals, flags, comments, and suggestions.
 * One data model, one storage format, one decoration system.
 *
 * Design principles:
 * - Atomic: Each mark is self-contained
 * - Granular: Target specific content precisely
 * - Composable: Different kinds combine for any workflow
 * - Extensible: Add new kinds without changing architecture
 */
/**
 * Get color for any key - returns known color or generates consistent one
 */
export declare function getMarkColor(key: string): string;
/**
 * Export known colors for static access (TypeScript type safety)
 */
export declare const MARK_COLORS: Record<string, string>;
/**
 * Built-in mark kinds
 */
export type MarkKind = 'authored' | 'approved' | 'flagged' | 'comment' | 'insert' | 'delete' | 'replace';
/**
 * Suggestion status lifecycle
 */
export type SuggestionStatus = 'pending' | 'accepted' | 'rejected';
/**
 * Orchestration metadata used to tag marks created by sub-agents.
 * These fields are optional and ignored by non-orchestrated flows.
 */
export interface OrchestratedMarkMeta {
    runId?: string;
    focusAreaId?: string;
    focusAreaName?: string;
    agentId?: string;
    proposalId?: string;
    provisional?: boolean;
    orchestrator?: boolean;
    /**
     * Debug metadata for orchestration reconciliation.
     * These fields are optional and safe to ignore in non-debug flows.
     */
    debugAutoFixedQuotes?: boolean;
    debugAutoFixedQuotesReason?: string;
}
/**
 * Data payload for different mark kinds
 */
/**
 * ProseMirror document range for precise positioning
 */
export interface MarkRange {
    from: number;
    to: number;
}
export interface CommentReply {
    by: string;
    text: string;
    at: string;
}
export interface AuthoredData {
}
export interface ApprovedData {
}
export interface FlaggedData {
    note?: string;
}
export interface CommentData extends OrchestratedMarkMeta {
    text: string;
    thread: string;
    resolved: boolean;
    replies?: CommentReply[];
}
export interface InsertData extends OrchestratedMarkMeta {
    content: string;
    status: SuggestionStatus;
}
export interface DeleteData extends OrchestratedMarkMeta {
    status: SuggestionStatus;
}
export interface ReplaceData extends OrchestratedMarkMeta {
    content: string;
    status: SuggestionStatus;
}
export type MarkData = AuthoredData | ApprovedData | FlaggedData | CommentData | InsertData | DeleteData | ReplaceData;
/**
 * A mark - metadata attached to specific content
 *
 * Position strategy:
 * - range: Primary position (ProseMirror document positions, not plain text offsets)
 * - quote: Fallback for recovery when positions shift
 * - orphaned: True when the referenced content no longer exists
 */
export interface Mark {
    id: string;
    kind: MarkKind;
    by: string;
    at: string;
    range?: MarkRange;
    quote: string;
    orphaned?: boolean;
    data?: MarkData;
}
/**
 * Document with marks
 */
export interface MarksDocument {
    version: number;
    marks: Mark[];
}
export interface StoredMark {
    kind?: MarkKind;
    by?: string;
    createdAt?: string;
    range?: MarkRange;
    /** Relative anchor start (char-offset form: `char:<offset>`). */
    startRel?: string;
    /** Relative anchor end (char-offset form: `char:<offset>`). */
    endRel?: string;
    text?: string;
    thread?: string | CommentReply[];
    threadId?: string;
    replies?: CommentReply[];
    resolved?: boolean;
    content?: string;
    status?: SuggestionStatus;
    note?: string;
    runId?: string;
    focusAreaId?: string;
    focusAreaName?: string;
    agentId?: string;
    proposalId?: string;
    provisional?: boolean;
    orchestrator?: boolean;
    debugAutoFixedQuotes?: boolean;
    debugAutoFixedQuotesReason?: string;
    /** Quote text for remote sync — allows recreating ProseMirror anchors on remote clients */
    quote?: string;
}
export interface MarksMetadataDocument {
    version: number;
    marks: Record<string, StoredMark>;
}
export declare function canonicalizeStoredMarks<T extends Record<string, unknown>>(metadata: T): T;
/**
 * Tracks a cluster of edits by the same actor within a short time window.
 * This is the metadata foundation for the future "layers" feature which
 * will answer questions about review depth, iteration count, and staleness.
 */
export interface EditSession {
    id: string;
    actor: string;
    timestamp: number;
    endTimestamp?: number;
    changeCount: number;
    characterDelta: number;
    source: 'file-watcher' | 'api' | 'keyboard' | 'paste';
    parentSessionId?: string;
    reviewType?: 'creation' | 'active-edit' | 'accept-only';
}
export declare function generateMarkId(): string;
export declare function generateThreadId(): string;
/**
 * Create an authored mark (replaces provenance spans)
 * Used to track who created content at the character level
 */
export declare function createAuthored(by: string, range: MarkRange, quote?: string): Mark;
/**
 * Create an approval mark
 */
export declare function createApproval(quote: string, by: string, range?: MarkRange): Mark;
/**
 * Create a flag mark
 */
export declare function createFlag(quote: string, by: string, note?: string, range?: MarkRange): Mark;
/**
 * Create a comment mark
 */
export declare function createComment(quote: string, by: string, text: string, threadId?: string, range?: MarkRange, meta?: OrchestratedMarkMeta): Mark;
/**
 * Create an insert suggestion mark
 */
export declare function createInsertSuggestion(quote: string, by: string, content: string, range?: MarkRange, meta?: OrchestratedMarkMeta): Mark;
/**
 * Create a delete suggestion mark
 */
export declare function createDeleteSuggestion(quote: string, by: string, range?: MarkRange, meta?: OrchestratedMarkMeta): Mark;
/**
 * Create a replace suggestion mark
 */
export declare function createReplaceSuggestion(quote: string, by: string, content: string, range?: MarkRange, meta?: OrchestratedMarkMeta): Mark;
/**
 * Normalize a quote for storage
 * - Normalize whitespace
 */
export declare function normalizeQuote(text: string): string;
/**
 * Find the position of a quote in document text
 * Returns { from, to } or null if not found
 */
export declare function resolveQuote(docText: string, quote: string): {
    from: number;
    to: number;
} | null;
/**
 * Resolve a mark's position in the document
 *
 * Strategy:
 * 1. If mark has range, check if content at range matches quote
 * 2. If match -> use range (positions are still valid)
 * 3. If no match or no range -> use quote resolution
 * 4. If quote not found -> mark is orphaned
 */
export declare function resolveMark(docText: string, mark: Mark, docSize?: number): {
    from: number;
    to: number;
    orphaned: boolean;
} | null;
/**
 * Mark a mark as orphaned (content deleted/moved)
 */
export declare function orphanMark(marks: Mark[], id: string): Mark[];
/**
 * Get all orphaned marks
 */
export declare function getOrphanedMarks(marks: Mark[]): Mark[];
/**
 * Get all non-orphaned marks
 */
export declare function getActiveMarks(marks: Mark[]): Mark[];
/**
 * Purge orphaned marks (clean up)
 */
export declare function purgeOrphanedMarks(marks: Mark[]): Mark[];
/**
 * Get all authored marks
 */
export declare function getAuthoredMarks(marks: Mark[]): Mark[];
/**
 * Get authored marks by actor
 */
export declare function getAuthoredByActor(marks: Mark[], actor: string): Mark[];
/**
 * Get human-authored marks
 */
export declare function getHumanAuthored(marks: Mark[]): Mark[];
/**
 * Get AI-authored marks
 */
export declare function getAIAuthored(marks: Mark[]): Mark[];
/**
 * Calculate authorship percentages from marks
 */
export declare function calculateAuthorshipStats(marks: Mark[], docLength: number): {
    humanPercent: number;
    aiPercent: number;
    humanChars: number;
    aiChars: number;
};
/**
 * Coalesce adjacent authored marks by the same actor
 * This keeps the mark count manageable
 */
export declare function coalesceAuthoredMarks(marks: Mark[]): Mark[];
/**
 * Update authored mark ranges after document edit
 * This is called when the document changes to keep ranges in sync
 */
export declare function updateMarkRangesAfterEdit(marks: Mark[], editFrom: number, editTo: number, newLength: number): Mark[];
/**
 * Get marks by kind
 */
export declare function getMarksByKind(marks: Mark[], kind: MarkKind): Mark[];
/**
 * Get marks by actor
 */
export declare function getMarksByActor(marks: Mark[], actor: string): Mark[];
/**
 * Get pending suggestions
 */
export declare function getPendingSuggestions(marks: Mark[]): Mark[];
/**
 * Get unresolved comments
 */
export declare function getUnresolvedComments(marks: Mark[]): Mark[];
/**
 * Get comments in a thread
 */
export declare function getThread(marks: Mark[], threadId: string): Mark[];
/**
 * Find a mark by ID
 */
export declare function findMark(marks: Mark[], id: string): Mark | undefined;
/**
 * Update a mark
 */
export declare function updateMark(marks: Mark[], id: string, updates: Partial<Mark>): Mark[];
/**
 * Remove a mark by ID
 */
export declare function removeMark(marks: Mark[], id: string): Mark[];
/**
 * Add a mark
 */
export declare function addMark(marks: Mark[], mark: Mark): Mark[];
/**
 * Accept a suggestion - update its status
 */
export declare function acceptSuggestion(marks: Mark[], id: string): Mark[];
/**
 * Reject a suggestion - update its status
 */
export declare function rejectSuggestion(marks: Mark[], id: string): Mark[];
/**
 * Modify a suggestion's content before accepting
 */
export declare function modifySuggestion(marks: Mark[], id: string, newContent: string): Mark[];
/**
 * Resolve a comment thread
 */
export declare function resolveComment(marks: Mark[], id: string): Mark[];
/**
 * Unresolve a comment thread
 */
export declare function unresolveComment(marks: Mark[], id: string): Mark[];
/**
 * Extract marks metadata from markdown content
 */
export declare function extractMarks(markdown: string): {
    content: string;
    marks: Record<string, StoredMark>;
    legacyMarks?: Mark[];
};
export declare function removeFinalizedSuggestionMetadata(marks: Record<string, StoredMark>): Record<string, StoredMark>;
/**
 * Embed marks metadata into markdown content
 */
export declare function embedMarks(markdown: string, marks: Record<string, StoredMark>): string;
/**
 * Check if markdown has embedded marks metadata
 */
export declare function hasMarks(markdown: string): boolean;
export declare function isAuthoredData(data: MarkData | undefined): data is AuthoredData;
export declare function isCommentData(data: MarkData | undefined): data is CommentData;
export declare function isInsertData(data: MarkData | undefined): data is InsertData;
export declare function isDeleteData(data: MarkData | undefined): data is DeleteData;
export declare function isReplaceData(data: MarkData | undefined): data is ReplaceData;
export declare function isFlaggedData(data: MarkData | undefined): data is FlaggedData;
/**
 * Check if actor is human
 */
export declare function isHuman(actor: string): boolean;
/**
 * Check if actor is AI
 */
export declare function isAI(actor: string): boolean;
/**
 * Check if actor is system
 */
export declare function isSystem(actor: string): boolean;
/**
 * Get actor display name
 */
export declare function getActorName(actor: string): string;
/**
 * Legacy provenance span structure (from old system)
 */
export interface LegacyProvenanceSpan {
    spanId: string;
    startOffset: number;
    endOffset: number;
    origin: string;
    authorId?: string;
    createdAt?: string;
}
/**
 * Legacy provenance data structure
 */
export interface LegacyProvenanceData {
    spans: LegacyProvenanceSpan[];
    metadata?: {
        humanPercent?: number;
        aiPercent?: number;
    };
}
/**
 * Migrate legacy provenance spans to authored marks (human-only)
 *
 * @param legacyData - The old provenance data structure
 * @param docText - The document text (for extracting quotes)
 * @returns Array of authored marks
 */
export declare function migrateProvenanceToMarks(legacyData: LegacyProvenanceData, docText: string): Mark[];
/**
 * Check if marks already contain migrated provenance
 */
export declare function hasMigratedProvenance(marks: Mark[]): boolean;
