// Generated by scripts/upstream-declarations.ts from the pinned proof-sdk-upstream sources.
// Do not edit; run `bun run upstream-declarations` after moving the pin.
/**
 * remark plugin + stringify handler for Proof mark spans.
 *
 * Parses inline <span data-proof="...">...</span> HTML into mdast nodes
 * and serializes proofMark nodes back to HTML spans.
 */
type ProofMarkNode = {
    type: 'proofMark';
    proof: string;
    attrs?: Record<string, string | null | undefined>;
    children?: Array<{
        type: string;
        value?: string;
        children?: any[];
    }>;
};
type MdastNode = {
    type: string;
    value?: string;
    children?: MdastNode[];
    [key: string]: unknown;
};
type MdastParent = {
    children: MdastNode[];
};
export declare function remarkProofMarks(): (tree: MdastNode) => void;
export declare function proofMarkHandler(this: any, node: ProofMarkNode, _parent?: unknown, state?: {
    containerPhrasing?: (node: ProofMarkNode, info?: Record<string, unknown>) => string;
}, info?: Record<string, unknown>): string;
export type { ProofMarkNode, MdastNode, MdastParent };
