services:
  nats:
    image: nats:2.11-alpine
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - ./data:/data
    command: ["-c", "/etc/nats/nats.conf", "-m", "8222"]
